include $(srctree)/drivers/misc/mediatek/Makefile.custom

ifeq ($(CONFIG_MTK_GF318),y)
obj-y	+= GF318/
endif
ifeq ($(CONFIG_MTK_GF516),y)
obj-y   += gf516m/
endif
ifeq ($(CONFIG_FINGERPRINT_GOODIX_GF_TEE),y)
obj-y	+=  gf/
endif

