#MODULE_NAME := gf318m-spi
#obj-m := $(MODULE_NAME).o

#$(MODULE_NAME)-objs := gf318m-spi.o \
#                       platform.o \
#                       gf318m_update.o

include $(srctree)/drivers/misc/mediatek/Makefile.custom
obj-y += gf318m-spi.o
obj-y += platform.o
obj-y += gf318m_update.o
